
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-University-Controller","number":30,"title":"Luis - University Controller and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-1/pull/30"},{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-UniversitySvc","number":29,"title":"Luis - UniversityQuery Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-1/pull/29"},{"author":{"id":"MDQ6VXNlcjMwMDUzNTkx","is_bot":false,"login":"ChrisWoolson","name":"Chris Woolson"},"headRefName":"Chris-TideController","number":26,"title":"Chris tide controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-1/pull/26"}]
